services:

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      DOMAIN: "https://${VW_HOSTNAME}"
      SIGNUPS_ALLOWED: "${SIGNUPS_ALLOWED:-false}"
      ADMIN_TOKEN: "${ADMIN_TOKEN_HASH}"
    volumes:
      - ./vw-data:/data

  caddy:
    image: caddy:alpine
    container_name: caddy
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "80:80"
      - "443:443"
    environment:
      VW_HOSTNAME: "${VW_HOSTNAME}"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - vaultwarden

  ddns:
    image: curlimages/curl:latest
    container_name: ddns
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      VW_HOSTNAME: "${VW_HOSTNAME}"
      DESEC_TOKEN: "${DESEC_TOKEN}"
    entrypoint: ["/bin/sh", "-c"]
    command:
      - 'while true; do curl -sS --ipv4 "https://update.dedyn.io/?hostname=$${VW_HOSTNAME}" --header "Authorization: Token $${DESEC_TOKEN}"; echo; sleep 300; done'

volumes:
  caddy_data:
  caddy_config:
